### ISSUE TITLE
cannot turn on release testing

### ISSUE THREAD

**Issue by XSven** [PerlToolsTeam/github_workflows#5]
I wanted to convince the called workflow _cpan-test.yml@main_ to execute my release tests. According to some perl consensus release test should run if the evnvironment variable RELEASE_TESTING is true.  I am unable to use the `env` keyword in a way that does not break my workflow. This

```yaml
name: CI

on:
  push:
    branches: [ development ]
  workflow_dispatch:

jobs:
  test:
    env:
      RELEASE_TESTING: 1
    uses: PerlToolsTeam/github_workflows/.github/workflows/cpan-test.yml@main
    with:
      perl_version: "[ 'latest' ]"
```

doesn't work. Any help to set this up properly are very much appreciated.
